### ISSUE TITLE
Support for Explanations for Correct and Incorrect Answers?

### ISSUE THREAD

**Issue by wlg13** [robbert-harms/ybe#1]
As I read the documentation, there is no support for explanations for correct and incorrect quiz answers. Explanations can help students learn, so it would be a plus if explanations were supported. Thanks!

**Comment by robbert-harms** [comment]
hi wlg13,

Thanks for your comments. Explanations are indeed currently not supported. I could add them though. My proposal would be something like this:

```yaml

- multiple_response:
    id: 2015_q1
    points: 1
    text: A simple multiple response question.
    answers:
        - answer:
            text: First answer
            correct: true
            hint: A hint for when the student chooses this answer
        - answer:
            text: Second answer
            hint: Another hint
        - answer:
            text: Third answer
            correct: true
    feedback:
        general: General feedback for after this question.
        on_correct: Feedback when the question was answered correctly.
        on_incorrect: Feedback shown when the question was answered incorrectly.
```

That is, every question will have a new section `feedback`. Feedback is meant to be shown after the question was answered. It will have at least the option `general` (for example, for open questions), while multiple choice and multiple response have the additional options `on_correct` and `on_incorrect`.

In addition, every multiple choice and multiple response question will have the item `hint`, which can for example be shown when that answer is selected. What to do with them exactly is up to the application using the Ybe database.

Would that cover your use cases?

Best,

Robbert

**Comment by wlg13** [comment]
Yes, this would be it. For a bit more information, my use case involved Canvas LMS Quizzes. I've got a number of quizzes in Canvas and I'd like to mix and match questions across them; it is a real chore in Canvas currently to do this. Thus, I could imagine many users for this code. I have enclosed a qti file generated in Canvas that includes the different types of feedback. Thank you.
[econ-104-sec-1-sp21-quiz-export (1).zip](https://github.com/robbert-harms/ybe/files/5877669/econ-104-sec-1-sp21-quiz-export.1.zip)

**Comment by robbert-harms** [comment]
Hi wlg13,

Yes, I think I understand. You want to do: QTI -> Ybe -> QTI and use Ybe for shuffling questions.  This is exactly where Ybe was made for. What is indeed currently missing is including hints and explanations. I did not need it for my work, but I will add it nonetheless. Let me get back to you in a few days, I will need to find some free time to implement it.

Best,

Robbert

**Comment by wlg13** [comment]
Yes, this is indeed the use case. Let me add that I'll promote it here at Penn State among my colleagues who use Canvas Quizzes and among learning designers (we have more than 100) who design online courses. Thank you.

**Comment by robbert-harms** [comment]
hi Bill,

I did some work towards implementing this feature request. Ybe now supports loading QTI with hints and explanations. For example, loading your QTI with the latest development branch results in:

```yaml
ybe_version: 0.2.3

info:
    title: ybe <--> Canvas Quiz Illustration
    date: 2021-01-28

questions:
- multiple_choice:
    id: g553e22aa1d8288d45ef090b0e8351ed0
    points: 1.0
    text: !html <div><p>Question 1.</p></div>
    feedback:
        general: !html <p><span>Here's the explanation for the correct and incorrect answer (or "general comments").</span></p>
        on_correct: !html <p>Here's the explanation for the correct answer.</p>
        on_incorrect: !html <p><span>Here's the explanation for the incorrect answer.</span></p>
    answers:
        - answer:
            text: A
            correct: true
            hint: !html <p>A is the answer because it is first.</p>
        - answer:
            text: B
            hint: !html <p>A is not the answer because it is second.</p>
        - answer:
            text: ''
        - answer:
            text: ''
```

It seems to cover the comments you mentioned. For the next iteration I'll add writing QTI's as well.

If you want to test this new feature, you will have to install manually using Github. When QTI writing is done I will push a new version.

If it is useful please do promote it. Maybe one day it can be added to Canvas as an additional import/export functionality.

Best, 

Robbert

**Comment by robbert-harms** [comment]
Hi Bill,

I added QTI writing support for the comments and hints. The updates are now in Ybe version 0.3.0. A full roundtrip conversion of your QTI file can be done with, for example, this code:

```python
from ybe import read_qti_zip, write_ybe_file, read_ybe_file, write_qti_zip
from ybe.lib.qti_writer import ConvertCanvasEquations

ybe_exam = read_qti_zip('example_with_comments.zip')
write_ybe_file(ybe_exam, 'example_with_comments.ybe', minimal=True)

ybe_from_ybe = read_ybe_file('example_with_comments.ybe')
write_qti_zip(ybe_from_ybe, 'example_with_comments_ybed.zip', text_formatter=ConvertCanvasEquations())
```

Let me know if this works for you. 

Looking forward to the news,

Robbert

**Comment by wlg13** [comment]
Robbert -

Happy to test. I tried first converting the attached (an actual file that I'll be working with) to yaml and there seems to be one issue. Question 6 (starts with "Which ones of the") has multiple answers and it didn't seem to convert correctly to the yaml format (see attached). To continue testing, in this yaml file one answer was selected as correct and then converted back to qti, but didn't get a thing when I loaded into Canvas. When I looked at the qti files, I didn't see any questions. Maybe worth a look? 
Thanks, 
   Bill
![question_in_yaml](https://user-images.githubusercontent.com/47542061/106348350-a1d90100-6293-11eb-9e30-3b048152ea68.png)
 
[econ-104-sec-1-fa20-quiz-export (5).zip](https://github.com/robbert-harms/ybe/files/5897437/econ-104-sec-1-fa20-quiz-export.5.zip)

**Comment by robbert-harms** [comment]
Hi Bill,

Thank you for your comments. There was indeed a problem parsing the correct answers of multiple response questions, in the case of comments to the questions. I fixed it and released version 0.3.1.

For me it now parses correctly. For the question you indicated the parsed yaml now reads:

```yaml
- multiple_response:
    id: ged19adfed59a65c6748955c50f09f9ac
    points: 2.0
    text: !html <div><p>Which ones of the following have ...</p></div>
    answers:
        - answer:
            text: real GDP
            correct: true
            hint: !html <p>The percent ...</p>
        - answer:
            text: real price
            hint: !html <p>There is no...</p>
        - answer:
            text: CPI
            correct: true
            hint: !html <p>The percentage ...</p>
        - answer:
            text: the GDP deflator
            correct: true
            hint: !html <p>The percentage...</p>
    feedback:
        general: !html <p>The percentage ...</p>
        on_correct: !html <p>The percentage change ...</p>
        on_incorrect: !html <p>The percentage change ...</p>
```

One thing I noticed, is that your YAML output reads ``text_html``. This is syntax from a previous version (0.2.*). In the newer versions I changed this to read ``text: !html ...``. To me this indicates that you are running with an older version. Could you update Ybe and try again? If you are using PIP, updating can be done with: 
``pip install --upgrade ybe``

Let me know how you fare,

Robbert

**Comment by wlg13** [comment]
Robbert -
We did update -- thanks. Now the qti --> ybe step works fine, but still getting no questions in the second step (that is, the qti file is generated, but has no questions). Perhaps something is amiss on our end? Thank you. - Bill

**Comment by robbert-harms** [comment]
Hi Bill,

Could you forward me three files, the original QTI, the Ybe you generated and the QTI obtained from the Ybe file? Using that I could cross reference the two QTI's and also check if your output is the same as my output.

Thanks for your help,

Best,

Robbert

Edit: I did try loading the previous QTI's you send me on canvas.instructure.com (including the Ybe converted) and for me they loaded perfectly, with all questions attached. Maybe there is a subtle detail we are missing here. I go to settings -> import course content and then select "QTI zip file".

**Comment by wlg13** [comment]
Robbert: I've asked my TA, who has been running the code, to respond. This has become sufficiently detailed for you and he to directly interact. I did upload the qti file into Canvas as you described. Thank you. - Bill

**Comment by nihal-mehta** [comment]
Hi Robbert - Please find attached the 3 files that you've asked for:

[3 files.zip](https://github.com/robbert-harms/ybe/files/5905331/3.files.zip)

**Comment by robbert-harms** [comment]
Hi Nihal,

Could you try with Ybe version 0.3.3?

I did notice a possible problem with the Ybe -> QTI conversion. I think it is fixed in this new version. Please give it a try.

In the new version, I changed the API a little bit. To convert from qti -> ybe -> qti you can use this example code:

```python
ybe_from_qti = read_qti_zip('../Original QTE.zip')
write_ybe_file(ybe_from_qti, '/tmp/original_qti.ybe')

ybe_from_ybe = read_ybe_file('/tmp/original_qti.ybe')
YbeToQTI_v1p2(convert_canvas_equations=True).convert(ybe_from_ybe, '/tmp/ybe_qti.zip')
```

Let me know if this works now,

Best,

Robbert

**Comment by nihal-mehta** [comment]
Hi Robbert,

I updated the package and used the code structure you shared. The QTI -> YBE conversion goes through properly but there still seems to be an issue with the YBE -> QTI step. (I can see the questions inside the final QTI file when I open it in notepad but it doesn't show anything when I open it in an xml viewer)

I have attached the 3 files in case you want to take look.

Thanks,
Nihal
[3 files.zip](https://github.com/robbert-harms/ybe/files/5923247/3.files.zip)

**Comment by robbert-harms** [comment]
Hi Nihal,

Thanks for your response, I finally see the problem. In the original QTI you provided there are several symbols like ``•``in the hint texts. Apparently, when you convert QTI -> Ybe, these symbols get translated into ``  ``, and stay like that in the Ybe -> QTI transformation. As such, the QTI can no longer be loaded. 

On my machine, the ``•`` are read and written correctly, which is why I was able to successfully convert your question bank and load it into Canvas.

Can you tell me what kind of OS you are running? Mac, Windows, Linux? And which version of that OS? I'll try to find a similar machine and try to repeat this error. Then, I can be sure that a fix would actually work for you as well.

Thanks for your help,

Robbert

**Comment by nihal-mehta** [comment]
Hi Robbert,

Okay, I see. Sometimes parsing of particular symbols can get problematic. I'm using a machine that is running Windows 10 Pro. Yes it would be great if you manage to find a fix that works for this setup. 

Thanks, 
Nihal

**Comment by robbert-harms** [comment]
Hi Nihal,

I think I fixed the encoding issue. Could you try again with Ybe version 0.3.4? It now works for me on my Windows 10 computer.

Best,

Robbert

**Comment by nihal-mehta** [comment]
Hi Robbert,

It worked properly this time. Thanks a lot for the continued help on this!

Best,
Nihal

**Comment by robbert-harms** [comment]
Hi Nihal,

Good to hear. Then I'll close this issue. Let me know if there is anything else. 

Best,

Robbert
